if: tag IS blank
language: node_js
node_js:
  - 'lts/*'

env:
  global:
    - CC_TEST_REPORTER_ID=3804e39d0ef9e56c92031dd53084f9af3454a4f408e62849b518cdfbe0516e1f

cache:
  yarn: true

before_install:
  - export PATH=$HOME/.yarn/bin:$PATH
  - curl -o- -L https://yarnpkg.com/install.sh | bash

install:
  - git config --global user.email $GITHUB_EMAIL
  - git config --global user.name $GITHUB_USER
  - git remote set-url origin "https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG.git"
  - yarn
  - lerna bootstrap
  - lerna run compile:cjs
  - lerna run compile:esm

jobs:
  include:
    - stage: test
      if: tag IS blank and branch != next
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script:
        - yarn run test
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
        - ./cc-test-reporter format-coverage -t lcov ./coverage/lcov.info
        - ./cc-test-reporter upload-coverage

    - stage: publish
      if: tag IS blank AND branch = next AND type != pull_request
      before_script:
        - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        - git checkout next
      script:
        - lerna version --conventional-commits --changelog-preset eslint --yes --allow-branch next
        - lerna publish from-package --yes
